### ISSUE TITLE
CTA: Button Shrinking/Wrapping

### ISSUE THREAD

**Issue by xjwllmsx** [xjwllmsx/top-landing-page#2]
The text in the CTA button wraps.

**Comment by xjwllmsx** [comment]
To prevent the text from wrapping, I added flex-wrap to the cta container. 

This is the updated code:
```css
.cta .container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    align-items: center;
    margin: 0 auto;
    background-color: #3882f6;
    border-radius: 8px;
    padding: 36px 32px;
    color: #f9faf8;
}
```
