### ISSUE TITLE
Random-Info: Images shrink

### ISSUE THREAD

**Issue by xjwllmsx** [xjwllmsx/top-landing-page#3]
The images in each card shrink slightly with a smaller viewport.

**Comment by xjwllmsx** [comment]
I added flex-wrap to the "cards" container to prevent the cards from shrinking when the viewport shrinks.

This is the original code:
```css
.cards {
    display: flex;
    flex-direction: row;
    justify-content: center;
    gap: 24px;
    width: 100%;
}
```

This is the code now with the flex-wrap insertion:
```css
.cards {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    gap: 24px;
    width: 100%;
}
```
