### ISSUE TITLE
Header: Button has shadow

### ISSUE THREAD

**Issue by xjwllmsx** [xjwllmsx/top-landing-page#6]
There is a shadow or border above the header button.

**Comment by xjwllmsx** [comment]
Below is the code that was adjusted (located on line 58):
```css
header .button {
    background-color: #3882f6;
    color: #f9faf8;
    font-weight: 600;
    padding: 6px 24px;
    border-radius: 8px;
}
```

I added the following declaration<sup>[1](https://stackoverflow.com/questions/32459646/removing-the-shadow-from-a-button)</sup> at the end of the block: 
```css
border: none
```
This declaration removes the border that is used as a default on the `<button>` tag. The complete declaration block looks like this:
```css
header .button {
    background-color: #3882f6;
    color: #f9faf8;
    font-weight: 600;
    padding: 6px 24px;
    border-radius: 8px;
    border: none;
}
```
