### ISSUE TITLE
Nav: Give links a :hover feature

### ISSUE THREAD

**Issue by xjwllmsx** [xjwllmsx/top-landing-page#7]
When hovering over the nav links, they should give an indication that they are clickable.

**Comment by xjwllmsx** [comment]
Added the following to line 42 in stylesheet:
```css
.nav-links a:hover {
    color: #969696;
}
```
